version: '3.3'

services:
  angular: 
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - '86:80'    
    container_name: ng-docker-example


  wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
    ports:
     - "89:80"
    volumes:
     - ./html:/var/www/html

  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql  
     
